##数据库配置
#spring.datasource.url=jdbc:mysql://localhost:3306/clawer?serverTimezone=Asia/Shanghai
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#
##配置.xml文件路径
#mybatis.mapper-locations=classpath:mapper/*.xml
##配置模型路径
#mybatis.type-aliases-package=com.grayliu.autoclawer.entity
server:
  port: 80

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: com.grayliu.autoclawer.entity

spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/clawer?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=GBK
    url: jdbc:mysql://127.0.0.1:3306/clawer?serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    username: root
    password: root
  freemarker:
      allow-request-override: false
      allow-session-override: false
      order: 1
      cache: true
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      enabled: true
      expose-request-attributes: false
      expose-session-attributes: false
      expose-spring-macro-helpers: true
      prefer-file-system-access: true
      suffix: .html
      template-loader-path: classpath:/templates/
      settings:
        output_format: HTMLOutputFormat
        template_update_delay: 0
        default_encoding: UTF-8
        url_escaping_charset: UTF-8
        classic_compatible: true
        number_format: ###

logging:
  path: D:\\demo
  file: demo.log
  level:
    root: info



